### ISSUE TITLE
Power penalty on Shekhtur's Spiral does not reduce Power below 1

### ISSUE THREAD

**Issue by tankbard** [tankbard/battlecon-ai#5]
Shekhtur: Spiral Burst (3 tokens)
Eligor: Chained Dash

Shekhtur antes a Malice token
Shekhtur antes a Malice token
Shekhtur antes a Malice token
Priorities:  3 | 8
Eligor is active
Shekhtur moves:

E.....S

Choose number of Vengeance tokens to spend for pulling:
[0-3]
0
Choose position to move to:
[1] .E....S    
[2] ..E...S    
[3] ...E..S    
1
Eligor moves:

.E....S

Shekhtur moves:

.E.S...

Shekhtur gets -3 power
Shekhtur hits
Eligor takes 1 damage

**Comment by BGazazel** [comment]
Hi. If Shekhtur use Unleashed, she will gain +1pow next beat. That can be the reason why Eligor took 1 dmg. Here works propertly:
http://i742.photobucket.com/albums/xx67/vancho_1/battlecon%20bugs/SpiralDmg.jpg

**Comment by tankbard** [comment]
In other news, I'm going to be attempting a half-rebuild of the whole thing to cause all effects to be printed out explicitly and to name their card sources, because playing this thing blind is incredibly obnoxious.

Thanks for the check.
