### ISSUE TITLE
Lymn Reverie at disparity 5+ execute effects at both lvls

### ISSUE THREAD

**Issue by BGazazel** [tankbard/battlecon-ai#6]
If i dont missunderstood the rules, only the effect of the last lvl should be applayed, not all of the previos effects. In this beat, Lymn's Reverie stun her AND took 2 dmg at Disparity 11:

http://i742.photobucket.com/albums/xx67/vancho_1/battlecon%20bugs/Lymn_Reverie_problem.jpg

**Comment by tankbard** [comment]
Working as intended; all Lymn's Disparity triggers are cumulative (e.g. at 6+ Disparity, Chimeric gets +6 Power, as noted on her UA card).

**Comment by BGazazel** [comment]
Thanks a lot. Miss that. :)
